# local state manager class for managing state in a persistent fashion
heron.class.state.manager:        com.twitter.heron.statemgr.zookeeper.curator.CuratorStateManager

#Un-comment the line below and add ZK IP address
#heron.statemgr.connection.string: "127.0.0.1:2181"
heron.statemgr.connection.string: "54.215.208.158:2181"


# path of the root address to store the state in a local file system
heron.statemgr.root.path:         "/heron"

####################################################################
# Following are config for Zk State Manager
####################################################################
heron.statemgr.zookeeper.is.initialize.tree:              True

heron.statemgr.zookeeper.session.timeout.ms:              30000

heron.statemgr.zookeeper.connection.timeout.ms:           30000

heron.statemgr.zookeeper.retry.count:                     10

heron.statemgr.zookeeper.retry.interval.ms:               10000

####################################################################
# Following are config for tunneling
####################################################################
# Whether we need tunnel if no direct access on zk server
heron.statemgr.is.tunnel.needed:           False

# The connection timeout in ms when trying to connect to zk server
heron.statemgr.tunnel.connection.timeout.ms:    1000

# The count of retry to check whether has direct access on zk server
heron.statemgr.tunnel.connection.retry.count:   2

# The interval in ms between two retry checking whether has direct access on zk server
heron.statemgr.tunnel.retry.interval.ms:        1000

# The count of retry to verify whether seting up a tunnel process
heron.statemgr.tunnel.verify.count:             10

