#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing,
#  software distributed under the License is distributed on an
#  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#  KIND, either express or implied.  See the License for the
#  specific language governing permissions and limitations
#  under the License.

# indicate the type of storage for checkpoint is local file system
heron.statefulstorage.classname:            "org.apache.heron.statefulstorage.localfs.LocalFileSystemStorage"

heron.statefulstorage.config:
  heron.statefulstorage.classpath:           ""
  heron.statefulstorage.localfs.root.path:   ~/.herondata/checkpoints
  heron.statefulstorage.localfs.max.checkpoints: 10

# Following are configs for socket between ckptmgr and stateful storage
heron.ckptmgr.network.write.batch.size.bytes: 32768

heron.ckptmgr.network.write.batch.time.ms: 16

heron.ckptmgr.network.read.batch.size.bytes: 32768

heron.ckptmgr.network.read.batch.time.ms: 16

heron.ckptmgr.network.options.socket.send.buffer.size.bytes: 655360

heron.ckptmgr.network.options.socket.receive.buffer.size.bytes: 655360

heron.ckptmgr.network.options.maximum.packetsize.bytes: 10485760
