# Configs for heron-tracker

## Contains the sources where the states are stored.
# Each source has these attributes:
# 1. type - type of state manager (zookeeper or file, etc.)
# 2. name - name to be used for this source
# 3. host - currently only used to connect to zk
# 4. port - port to connect to
# 5. rootpath - where all the states are stored
statemgrs:
  -
    type: "file"
    name: "local"
    host: "localhost"
    port: 0
    rootpath: "~/.herondata/repository/state/local"
    tunnelhost: "localhost"

# The URL that points to a topology's metrics dashboard.
# This value can use following parameters to create a valid
# URL based on the topology. All parameters are self-explanatory.
# These are found in the execution state of the topology.
#   {cluster}
#   {environ}
#   {jobname} - Same as topology name
#   {role}
#   {submission_user}
viz.url.format: "http://localhost/{cluster}/{environ}/{jobname}/{role}/{submission_user}"
